version: '3.1'
services:
  app:
   container_name: docker-jenkins-test
   image: docker-jenkins
   build:
     context: .
     dockerfile: Dockerfile
   ports:
     -  '8085:8085'
   depends_on:
     - dbpostgresdldockerjenkins
  dbpostgresdldockerjenkins :
    container_name: docker-jenkins-db
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tqll
      POSTGRES_DB: docker-jenkins-test_db
    volumes:
      - ./db-data:/var/lib/postgresql/data
